"use strict";
// Static C# contracts, not Unity compilation or C# execution.
const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path");
const read = file => fs.readFileSync(path.resolve(__dirname, "../..", file), "utf8");
const config = read("Assets/Scripts/Runtime/Features/VerificationSessionConfiguration.cs");
const guard = read("Assets/Scripts/Runtime/Features/VerificationRemoteGuard.cs");
const editor = read("Assets/Editor/OnlineRecordVerificationWindow.cs");
const game = read("Assets/Scripts/Runtime/Systems/GameSystem.cs");
const auth = read("Assets/Scripts/Runtime/Features/UgsOnlineAuthenticationGateway.cs");
const transport = read("Assets/Scripts/Runtime/Features/UgsOnlineRecordTransport.cs");
for (const phase of ["RequestStarted", "ClientTimeout", "SdkTimeout", "ResponseReceived", "RequestFailed", "LateResponseReceived", "LateRequestFailed"])
  assert.ok(transport.includes(`"${phase}"`));
assert.ok(transport.includes("if (sequence != _requestSequence) return;"));
assert.ok(transport.includes("requestError.ErrorCode"));
for (const diagnostic of ["RequestOrdinal=", "ClientElapsedMs=", "ServerElapsedMs=", "ServerServiceCalls="])
  assert.ok(transport.includes(diagnostic));
assert.ok(transport.includes("Stopwatch elapsed = Stopwatch.StartNew()"));
assert.ok(transport.includes("response == null || !response.serverTimingPresent ? -1"));
assert.ok(transport.includes("if (sequence != _requestSequence) return;"));
assert.ok(!transport.includes("error.Message") && !transport.includes("error.ToString()"));
assert.ok(editor.includes("_moduleTransport.LastDiagnostic"));
const compare = read("Assets/Scripts/Runtime/Features/VerificationRecordComparison.cs");
const pendingFixtureTests = read("Assets/Tests/EditMode/VerificationSessionTests.cs");
const pendingFixture = pendingFixtureTests.slice(pendingFixtureTests.indexOf("private static LocalRecordRepository PendingLocal"),
  pendingFixtureTests.indexOf('[TestCase("Submitted", "PENDING_SUBMISSION_CONFIRMED"'));
assert.ok(pendingFixture.indexOf('local.CreateSaveData("verification-local-owner"') >= 0);
assert.ok(pendingFixture.indexOf("local.CreateSaveData") < pendingFixture.indexOf("TryCreateStageCandidate"),
  "Pending fixture must initialize its local owner before creating a candidate");
assert.ok(pendingFixtureTests.includes("LocalRecordRepository local = PendingLocal(false);"));
const pendingRetry = read("Assets/Scripts/Runtime/Features/VerificationPendingRetry.cs");
assert.equal((pendingRetry.match(/await online\.SubmitAsync\(candidate\)/g) || []).length, 1);
assert.ok(!pendingRetry.includes("TryEnqueuePending") && !pendingRetry.includes("Guid.NewGuid"));
assert.ok(!/\bfor\s*\(|\bwhile\s*\(/.test(pendingRetry));
assert.ok(pendingRetry.indexOf("result.Result != E_RecordSubmissionResult.Submitted") < pendingRetry.indexOf("local.TryRemovePending"));
assert.ok(pendingRetry.includes("ReferenceEquals(binding, local.OnlineAccount)"));
assert.ok(editor.includes('ProbePhase2(8)'));
const retryProbe = editor.slice(editor.indexOf("if (probe == 8)"), editor.indexOf("if (probe == 4 || probe == 7)"));
assert.ok(retryProbe.includes("_guard, _guard"));
assert.ok(!retryProbe.includes("_account.TryAuthenticateAsync") && !retryProbe.includes("Guid.NewGuid"));
assert.ok(config.includes('"Prototype8Verification"'));
for (const profile of ["flow-state-phase2-a", "flow-state-phase2-b", "flow-state-verification"]) assert.ok(config.includes(profile));
assert.ok(config.includes("!isAutomatedTest && !isBatchMode && isPlaying && isIsolated"));
assert.ok(config.includes("UnityEditor.SessionState.GetBool(EditorIsolationKey, false)"));
assert.ok(config.includes("projectId == OnlineRecordConfiguration.ProjectId"));
assert.equal(config.split("public static VerificationSessionConfiguration FromArguments").length - 1, 1);
assert.ok(config.includes('"--fs-verification-session="'));
assert.ok(guard.includes("_isAllowed != null && _isAllowed()"));
assert.equal((guard.match(/if \(!IsAllowed\)/g) || []).length, 4);
assert.ok(guard.includes("return IsAllowed ? result"));
assert.ok(guard.includes("IsAllowed ? RunWithinOperationAsync(() => _authentication.TryClearSessionAsync"));
assert.ok(guard.includes("OperationTimeoutMilliseconds = 5000"));
assert.ok(guard.includes("Task.WhenAny(work, deadline)"));
assert.ok(guard.indexOf("deadline.IsCompleted") < guard.indexOf("Task<T> work = start()"));
assert.ok(transport.includes("ResponseTimeoutMilliseconds = 5000"));
assert.equal((editor.match(/_guard\.BeginOperation\(\)/g) || []).length, 2);
assert.equal((editor.match(/finally \{ FinishPhase2Operation\(\); \}/g) || []).length, 2);
assert.ok(editor.includes("_guard.WaitWithinOperationAsync(() => Task.Delay(milliseconds))"));
assert.ok(editor.includes("request.Abort(); throw new TimeoutException();"));
assert.ok(editor.includes("request.timeout = 5;"));
assert.ok(editor.includes("WindowOperationTimeoutMs="));
assert.ok(auth.includes("_initializedProfile != _profile"));
assert.ok(auth.includes("AuthenticationService.Instance.Profile != _profile"));
for (const failure of ["ProjectMismatch", "UnsupportedProfile", "InitializedProfileMismatch", "ExternalServicesInitialization", "SdkProfileMismatch"])
  assert.ok(auth.includes(`failure = "${failure}"`));
assert.ok(auth.includes("requestError.ErrorCode"));
assert.ok(auth.includes("AuthElapsedMs="));
assert.ok(!auth.includes("error.Message") && !auth.includes("error.ToString()"));
assert.ok(editor.includes("_authenticationGateway.LastDiagnostic"));
assert.ok(game.includes("new UgsOnlineAuthenticationGateway(_verificationSession.Profile)"));
assert.ok(game.includes("new PersistentLocalSaveFileStore(_verificationSession.DirectoryPath)"));
assert.ok(game.indexOf("if (UseIsolatedRecordsForPlayModeTests || VerificationSessionConfiguration.IsEditorIsolationArmed)") < game.indexOf("IOnlineAuthenticationGateway authentication = _verificationSession"));
assert.ok(game.includes("saveFileStore = (UseIsolatedRecordsForPlayModeTests || VerificationSessionConfiguration.IsEditorIsolationArmed)"));
assert.ok(editor.includes("Play 전 격리 실행 예약 (원격 호출 없음)"));
assert.ok(editor.includes("playModeStateChanged += HandlePlayModeStateChanged"));
assert.ok(editor.includes("playModeStateChanged -= HandlePlayModeStateChanged"));
assert.ok(editor.includes("!Application.isPlaying || !VerificationSessionConfiguration.IsEditorIsolationArmed"));
assert.ok(editor.includes('[MenuItem("Flow State/Online Record Verification")]'));
assert.ok(editor.includes("private bool _phase2 = true"));
assert.ok(editor.includes("private bool _remoteConsent;"));
assert.ok(editor.includes("EditorGUILayout.BeginScrollView(_scrollPosition)"));
assert.ok(editor.includes("finally { EditorGUILayout.EndScrollView(); }"));
assert.ok(editor.includes("style.CalcHeight(new GUIContent(text), ContentWidth)"));
assert.equal((editor.match(/GUILayout\.Button\(/g) || []).length, 1, "All buttons must use wrapped layout helper");
assert.ok(editor.includes("EditorGUILayout.ToggleLeft(new GUIContent(text), value, style"));
assert.ok(editor.includes("DrawSelectableValue(_configuration.SavePath, true)"));
assert.ok(editor.includes("전체 메시지 복사 (민감 정보 제외)"));
assert.ok(editor.includes("전체 메시지 복사 (민감 정보 포함 / 로컬 전용)"));
assert.ok(editor.includes("EditorUtility.DisplayDialog"));
assert.equal((editor.match(/EditorGUILayout\.HelpBox\(/g) || []).length, 1);
assert.ok(editor.includes("BuildVisibleMessageReport(bool includeSensitive)"));
assert.ok(!editor.includes("GUILayout.Height(36)"));
assert.ok(editor.includes("EditorGUILayout.TextArea(_baselineInput"));
assert.ok(editor.includes("ACCOUNT_NOT_READY / "));
assert.ok(editor.includes("SafeDiagnosticReason(_account.ViewState.Reason)"));
assert.ok(!editor.includes("/ " + "실제 상태는 계정 패널에서 확인"));
assert.ok(editor.includes("_remoteConsent = false;"));
assert.ok(editor.includes('api.GetMethod("IsRunActive", BindingFlags.Static | BindingFlags.NonPublic)'));
assert.ok(editor.includes("if (method == null) return true;"));
assert.ok(!/\bApplication\.isPlayingOrWillChangePlaymode/.test(editor));
assert.ok(editor.includes("EditorApplication.isPlayingOrWillChangePlaymode"));
const prepare = editor.slice(editor.indexOf("private void PreparePhase2()"), editor.indexOf("private void ClearPhase2Presentation()"));
assert.ok(prepare.includes("if (IsAutomatedExecution()"));
assert.ok(prepare.includes("new VerificationRemoteGuard(() => generation == _sessionGeneration && CanRunPhase2()"));
assert.ok(editor.includes("EnterPlayModeOptions.DisableDomainReload | EnterPlayModeOptions.DisableSceneReload"));
assert.ok(!/await |\.InitializeAsync\(|\.TryAuthenticateAsync\(|\.OpenAsync\(/.test(prepare));
assert.ok(prepare.includes("Guid.NewGuid().ToString"));
assert.ok(prepare.includes("if (!_isolatedLocal.CanUseOnlineData)"));
assert.ok(editor.includes("new AccountTransferController(_isolatedLocal, _account, this"));
assert.ok(editor.includes("PUBLIC_ME_SCORE_ACCEPTED_AT_PRESERVED"));
assert.ok(editor.includes("ORIGINAL_INACTIVE_STATUS"));
assert.ok(editor.includes("ORIGINAL_QUERY_FAILED"));
const originalProbe = editor.slice(editor.indexOf("if (probe == 4 || probe == 7)"), editor.indexOf("if (probe == 1)"));
assert.ok(originalProbe.includes("_guard.TryAuthenticateAsync()"));
assert.ok(!originalProbe.includes("_account.TryAuthenticateAsync()"));
const statusOnly = originalProbe.slice(originalProbe.indexOf("if (probe == 4)"), originalProbe.indexOf("OnlineRecordConfiguration.TryGetLeaderboardId"));
assert.ok(statusOnly.includes("get-account-transfer-status") && statusOnly.includes("return;"));
assert.ok(!statusOnly.includes("query-records"));
assert.equal((originalProbe.match(/get-account-transfer-status/g) || []).length, 1);
assert.equal((originalProbe.match(/query-records/g) || []).length, 1);
const baselineProbe = editor.slice(editor.indexOf("if (probe == 1)"), editor.indexOf("if (!(await _account.TryAuthenticateAsync())"));
assert.ok(baselineProbe.includes("_guard.TryAuthenticateAsync()"));
assert.ok(baselineProbe.includes("authenticated.PlayerId != _isolatedLocal.OnlineAccount.PlayerId"));
assert.ok(!baselineProbe.includes("_account.TryAuthenticateAsync()"));
assert.ok(!baselineProbe.includes("_records.GetPersonalBestAsync"));
assert.equal((baselineProbe.match(/query-records/g) || []).length, 1);
assert.ok(baselineProbe.includes("GetPreservationFailureReason"));
assert.ok(baselineProbe.includes("comparedMe.entries[0].publicPlayerNumber"));
assert.ok(!/\bOnlineLeaderboardResult\s+current\b/.test(baselineProbe),
  "Read-only branch must not shadow the enclosing current local (CS0136)");
assert.ok(!/\bcurrent\b/.test(baselineProbe.replace(/\/\/[^\r\n]*/g, "")),
  "Read-only branch must consistently use its distinct comparedMe local");
assert.ok(baselineProbe.includes("get-public-player-number"));
assert.ok(editor.includes("operation.completed += HandleCompleted"));
assert.ok(editor.includes("operation.completed -= HandleCompleted"));
assert.ok(compare.includes("baseline.publicPlayerNumber != number"));
assert.ok(compare.includes("baseline.boardId != boardId"));
assert.ok(compare.includes("before.acceptedAt == after.acceptedAt"));
assert.ok(compare.includes("public static bool IsSubmittedMe"));
assert.equal((compare.match(/public static string GetStageProbeBlockReason\(/g) || []).length, 1,
  "VerificationRecordComparison must declare GetStageProbeBlockReason only once (CS0111 regression)");
assert.equal((compare.match(/public static bool IsSubmittedMe\(/g) || []).length, 1,
  "VerificationRecordComparison must declare IsSubmittedMe only once (CS0111 regression)");
assert.ok(compare.includes("entry.score == expectedScore && entry.acceptedAt > 0"));
for (const failure of ["STAGE_PROBE_REQUIRES_EMPTY_ME", "STAGE_PROBE_QUERY_FAILED", "STAGE_PROBE_INVALID_ME"])
  assert.ok(compare.includes(failure));
assert.ok(editor.includes("Stage 제출 전 조회만 확인 (기록 제출 없음)"));
assert.equal((editor.match(/private static string SafeQueryPhase\(/g) || []).length, 1);
assert.ok(editor.includes("SafeQueryPhase(result.queryPhase)"));
assert.equal((editor.match(/private static string SafeQueryFault\(/g) || []).length, 1);
assert.ok(editor.includes("SafeQueryFault(result.queryFault)"));
assert.ok(editor.includes("result.serviceStatus.ToString()"));
assert.ok(editor.includes("GetStageProbeBlockReason(before, probe != 2)"));
assert.ok(editor.indexOf("if (probe == 6)") < editor.indexOf("RecordSubmissionPolicy.TryCreateStageCandidate"));
assert.ok(editor.includes("IsSubmittedMe(submitted, _account.ViewState.NumberText, expectedScore)"));
assert.ok(editor.includes("submitted.entries[0].acceptedAt == before.entries[0].acceptedAt"));
assert.ok(editor.includes("SERVER_SUBMITTED_AND_ME_VERIFIED"));
assert.ok(editor.includes("Leaderboard"));
assert.ok(!compare.includes("before.rank == after.rank"));
const cache = path.resolve(__dirname, "../../Library/PackageCache");
if (fs.existsSync(cache)) {
  const name = fs.readdirSync(cache).find(name => name.startsWith("com.unity.test-framework@"));
  if (name) assert.ok(fs.readFileSync(path.join(cache, name, "UnityEditor.TestRunner/Api/TestRunnerApi.cs"), "utf8").includes("internal static bool IsRunActive()"));
}
const files = ["Assets/Scripts/Runtime/Features/VerificationSessionConfiguration.cs", "Assets/Scripts/Runtime/Features/VerificationRemoteGuard.cs", "Assets/Scripts/Runtime/Features/VerificationRecordBaseline.cs", "Assets/Scripts/Runtime/Features/VerificationRecordComparison.cs", "Assets/Tests/EditMode/VerificationSessionTests.cs", "Assets/Tests/PlayMode/VerificationToolIsolationTests.cs", "Assets/Editor/OnlineRecordVerificationWindow.cs", "Assets/Scripts/Runtime/Features/UgsOnlineAuthenticationGateway.cs", "Assets/Scripts/Runtime/Features/PersistentLocalSaveFileStore.cs", "Assets/Scripts/Runtime/Systems/GameSystem.cs"];
const guids = [];
for (const file of files) {
  const source = read(file); assert.ok(!/System\.Linq|\?\.|\?\?/.test(source), file);
  const plain = source.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\/\/[^\r\n]*|\/\*[\s\S]*?\*\//g, "");
  const stack = [], pairs = { ")": "(", "}": "{", "]": "[" };
  for (const char of plain) { if ("({[".includes(char)) stack.push(char); if (pairs[char]) assert.equal(stack.pop(), pairs[char], file); }
  assert.equal(stack.length, 0, file);
  const guid = read(`${file}.meta`).match(/guid: ([a-f0-9]{32})/); assert.ok(guid); guids.push(guid[1]);
}
assert.equal(new Set(guids).size, files.length);
const edit = read("Assets/Tests/EditMode/VerificationSessionTests.cs"), play = read("Assets/Tests/PlayMode/VerificationToolIsolationTests.cs");
assert.ok(edit.includes("DefaultDisabledGuard_MakesZeroAuthenticationTokenOrTransportCalls"));
assert.ok(edit.includes("PermissionRevokedWhileAuthenticating_BlocksResultAndFollowupCalls"));
assert.ok(play.includes("VerificationWindow_AutomaticTestCannotPrepareSdkOrPersistentSession"));
assert.ok(play.includes("VerificationWindow_MessageReportIncludesOnlyPermittedContent"));
console.log(`PASS verification tool source contracts. Prepared only: Edit ${[...edit.matchAll(/\[Test\]|\[TestCase\(/g)].length}, Play ${[...play.matchAll(/\[UnityTest\]|\[Test\]|\[TestCase\(/g)].length}; Unity execution NOT performed.`);
